export const products = [
  {
    id: "1",
    name: "Cherry Steak",
    title: "Bold and flavorful",
    desc: "A bold steak with a sweet and smoky twist. Grilled to perfection and topped with a luscious cherry glaze. A tender, perfectly cooked steak elevated by a rich, ruby-red cherry reduction",
    srcUrl: "/cherrySteak.jpg",
    category: "steak",
    ingredients: "Aged beef (100%): salt: black peper",
    price: 45,
    sold: 9853,
  },
  {
    id: "2",
    name: "Smoked Steak",
    title: "Grilled and smoked steak",
    desc: "A perfectly cooked steak, seared to a golden brown crust and juicy on the inside. The rich, savory flavors of the meat are enhanced by a simple seasoning of salt and pepper. Each bite is a tender, flavorful experience",
    srcUrl: "/steakjuice.jpg",
    category: "steak",
    ingredients: "Aged beef (100%): salt: black peper",
    price: 45,
    sold: 11853,
  },
  {
    id: "3",
    name: "Tender Kabab",
    title: "Tender chunks of marinated meat",
    desc: "A classic Turkish dish featuring succulent pieces of marinated meat, carefully threaded onto skewers and grilled over an open flame. The result is a smoky, flavorful delight that's tender on the inside and crispy on the outside",
    srcUrl: "/kababonfire.jpg",
    category: "kabab",
    ingredients: "Aged beef (100%): salt: black peper",
    price: 45,
    sold: 27853,
  },
  {
    id: "4",
    name: "Platter Special",
    title: "Our generous special family platter",
    desc: "A feast for the whole family! Our generous platter is loaded with a variety of your favorite dishes, perfect for sharing. Enjoy a delicious assortment of [list of dishes: steak, suasages, kabab skews, served with rice, salad and bread]",
    srcUrl: "/mix-grill-color.jpg",
    category: "platter",
    ingredients: "Mixed meat (100%): salt: black peper, specail marinate",
    price: 80,
    sold: 6853,
  },
  {
    id: "5",
    name: "Grilled sausages",
    title: "Grilled sausages, sizzling with flavor",
    desc: "Succulent sausages, expertly grilled over an open flame until golden brown and crispy. Each bite is a burst of flavor, with a smoky char and a juicy, meaty center.",
    srcUrl: "/grilled-sausage.jpg",
    category: "sausage",
    ingredients: "Meat (90%): fat: (10%), natural flavors",
    price: 25,
    sold: 12853,
  },
  {
    id: "6",
    name: "Special Burger",
    title: "Juicy beef patty with chef's specail flavors",
    desc: "The combination of flavors and textures is what makes a special burger so satisfying. The savory beef patty, the gooey melted meat, the crisp vegetables, and the tangy sauces all come together to create a delicious and iconic dish.",
    srcUrl: "/challenger.jpg",
    category: "burger",
    ingredients: "Meat (100%): natural flavors",
    price: 30,
    sold: 25853,
  },
  {
    id: "7",
    name: "Limited Burger",
    title: "The patties are sandwiched between a sesame seed bun",
    desc: "Next level with double the beefy goodness. It features two juicy beef patties, each topped with a slice of melted cheese, typically American cheese, cheddar, or Swiss.  1  The patties are sandwiched between a sesame seed bun, and often accompanied by classic toppings like lettuce, tomato, onion, pickles, ketchup, and mustard. 2 ",
    srcUrl: "/Dreamer.jpg",
    category: "burger",
    ingredients: "Meat (100%): natural flavors",
    price: 25,
    sold: 11853,
  },

  {
    id: "8",
    name: "Double Burger",
    title:
      "It features two juicy beef patties, each topped with a slice of melted cheese",
    desc: "The double patty adds a satisfying heft and richness to the burger, making it a meal in itself. It's a popular choice for those with hearty appetites or a craving for a truly indulgent burger experience",
    srcUrl: "/doubleBurger.jpg",
    category: "burger",
    ingredients: "Meat (100%): natural flavors",
    price: 25,
    sold: 10853,
  },
  {
    id: "9",
    name: "Cheese Burger",
    title: "Classic food, consisting of a juicy beef patty with melted cheese",
    desc: "A cheeseburger is a classic fast food staple, consisting of a juicy beef patty topped with a slice of melted cheese, typically American cheese, cheddar, or Swiss. 1 It's usually served on a sesame seed bun with a variety of toppings like lettuce, tomato, onion, pickles, ketchup, and mustard.The combination of flavors and textures is what makes a cheeseburger so satisfying. The savory beef patty, the gooey melted cheese, the crisp vegetables, and the tangy sauces all come together to create a delicious and iconic dish.",
    srcUrl: "/cheeseburger.jpg",
    category: "burger",
    ingredients: "Meat (100%): natural flavors",
    price: 20,
    sold: 5853,
  },
  {
    id: "10",
    name: "Grilled steak",
    title: "The most popular cuts of beef for grilling are ribeye",
    desc: "A grilled beef steak is a classic dish that is enjoyed by people all over the world. It is a versatile dish that can be cooked to any degree of doneness, from rare to well done. The most popular cuts of beef for grilling are ribeye, New York strip, and filet mignon.",
    srcUrl: "/beefSteak.jpg",
    category: "steak",
    ingredients: "Aged beef (100%): natural flavors",
    price: 50,
    sold: 10153,
  },
  {
    id: "11",
    name: "Tender steak",
    title: "Texture of the tender steak with beautiful golden brown color",
    desc: "Tender steak should have a beautiful golden brown color. It should also have grill marks on the surface of the steak. The texture of a tender steak is tender and juicy. It should be cooked to the desired degree of doneness",
    srcUrl: "/fillet-of-beef.jpg",
    category: "steak",
    ingredients: "Aged beef (100%): natural flavors",
    price: 50,
    sold: 19153,
  },
  {
    id: "12",
    name: "Perfect steak",
    title: "Unique blend of savory and flora",
    desc: "A steak marinated in rose water and then grilled or pan-seared to perfection. The rose water adds a delicate floral flavor to the meat, while the grilling process creates a crispy exterior and a juicy interior. This dish is often served with a side of roasted vegetables or a light salad",
    srcUrl: "/jucieSteak.jpg",
    category: "steak",
    ingredients: "Aged beef (100%): natural flavors",
    price: 50,
    sold: 69153,
  },
  {
    id: "13",
    name: "Kabab Skews",
    title: " It is made by marinating chunks of meat",
    desc: " Kabab on Skews is a popular dish in many parts of the world. It is made by marinating chunks of meat, such as lamb, beef, or chicken, in a flavorful blend of spices and then grilling them on skewers over an open flame. The result is a juicy and tender kebab with a smoky flavor.",
    srcUrl: "/shish-kebab.jpg",
    category: "kabab",
    ingredients: "Meat (100%): salt: black peper",
    price: 55,
    sold: 17858,
  },
  {
    id: "14",
    name: "Shish Kabab",
    title: "Shish kebab with a smoky flavor.",
    desc: "Kabab is a popular dish in many parts of the world, especially in the Middle East, South Asia, and Southeast Asia. It is made by marinating chunks of meat, such as lamb, beef, chicken",
    srcUrl: "/shishKabab.jpg",
    category: "kabab",
    ingredients: "Meat (100%): salt: black peper",
    price: 45,
    sold: 53858,
  },
  {
    id: "15",
    name: "Mixed grill",
    title: "A mix grill is a delicious and satisfying meal.",
    desc: "Grilled beef steaks, such as ribeye, sirloin, or fillet mignon, are a popular choice for mix grills. They are typically cooked to medium-rare or medium-well. A mix grill is a delicious and satisfying meal that typically includes a variety of grilled meats.",
    srcUrl: "/mix-grill.jpg",
    category: "platter",
    ingredients: "Mixed meat (100%): salt: black peper",
    price: 75,
    sold: 10058,
  },
  {
    id: "16",
    name: "Family Platter",
    title: "Typically includes a variety of grilled meats.",
    desc: "Grilled beef steaks, such as ribeye, sirloin, or fillet mignon, are a popular choice for mix grills. They are typically cooked to medium-rare or medium-well. A mix grill is a delicious and satisfying meal that typically includes a variety of grilled meats.",
    srcUrl: "/familyPlatter.jpg",
    category: "platter",
    ingredients: "Mixed meat (100%): salt: black peper",
    price: 95,
    sold: 25058,
  },
  {
    id: "17",
    name: "Red sausages",
    title: "Classic comfort food that can be enjoyed by people of all ages",
    desc: "Grilled sausages are a classic comfort food that can be enjoyed by people of all ages. They are typically made from ground beef, or lamb, and are seasoned with a variety of spices, such as salt, pepper, garlic, and herbs.",
    srcUrl: "/grillRedSuasage.jpg",
    category: "sausage",
    ingredients: "Meat (100%): salt: black peper",
    price: 30,
    sold: 15058,
  },
  {
    id: "18",
    name: "Smoky sausages",
    title: "The sausages are cooked over an open flame.",
    desc: "A classic and delicious way to cook sausages, the smoky flavor of the grill adds a unique twist to the traditional taste. The sausages are cooked over an open flame, allowing the meat to absorb the smoky flavor of the wood or charcoal. The result is a juicy and flavorful sausage that is perfect for any occasion.",
    srcUrl: "/smokySausages.jpg",
    category: "sausage",
    ingredients: "Meat (100%): salt: black peper",
    price: 30,
    sold: 85058,
  },
];

export const customers = [
  {
    id: "1",
    name: "Jane Doe",
    email: "jane@email.com",
    comment:
      "This steak was absolutely phenomenal! The grill marks were perfectly charred, giving it that smoky flavor.",
    imgSrc: "/janeDoe.avif",
    date: "08/12/2024",
    time: "15:00",
    people: 3,
    uniqueId: "AI#45df",
  },
  {
    id: "2",
    name: "Barry Smith",
    email: "barry@email.com",
    comment:
      "The crust was crispy and flavorful, and the inside was cooked exactly to my preferred doneness—juicy, tender, and full of flavor. The seasoning was spot on",
    imgSrc: "/barrySmith.avif",
    date: "08/12/2024",
    time: "15:30",
    people: 2,
    uniqueId: "AI#j5df",
  },

  {
    id: "3",
    name: "Bob Tucker",
    email: "bob@email.com",
    comment:
      "These sausages were absolutely delicious! The casing had the perfect snap, and the inside was juicy and packed with flavor. The seasoning was just right—not too overpowering but with a perfect balance of herbs and spices that complemented the meat beautifully.",
    imgSrc: "/bobTucker.avif",
    date: "08/12/2024",
    time: "17:00",
    people: 1,
    uniqueId: "AI#u9df",
  },
  {
    id: "4",
    name: "Alex Anderson",
    email: "alex@email.com",
    comment:
      "Every bite was a perfect balance of smoky, savory, and tender. Definitely one of the best burger I’ve had!",
    imgSrc: "/alexAnderson.avif",
    date: "08/12/2024",
    time: "16:00",
    people: 4,
    uniqueId: "AI#487f",
  },
];
